### PR TITLE
chg: :art: :boom: black formatting update

### PR DESCRIPTION
**Pull request by olivmindee**
# PR Details

Black 21 implementation
- 🎨 code reformatting
- creates pyproject.toml with black default config @ 88 lines
- add black to requirements.dev.txt

## Motivation and Context

Facilitate collaborative contributions when coding.

## Types of changes

- [x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by fharper** [comment]
Seems like you also work on that @ianardee ?

**Comment by olivmindee** [comment]
I guess you can close this one and use the branch from @ianardee , still the later needs to reformat the `tests` folder and the `setup.py` file.

**Comment by fharper** [comment]
I'll let @ianardee decide what to do about this PR :)

**Comment by ianardee** [comment]
@olivmindee sorry I hadn't seen this PR. It would be better to take this one since my branch now has other things in it.
Can you fix the conflict so I can merge?

**Comment by olivmindee** [comment]
closing, using @ianardee PR for black formatting

**Pull request closed without merging**
