### PR TITLE
Invoice fixes

### PR DESCRIPTION
**Pull request by ianardee**
# Invoice fixes

## Description

* Better unit tests for invoice PDFs, counting pages.
* Fix for `customer_company_registration` being a `List` of values, having a type.
* Refactor base `Field` class, runtime attribute definitions are evil.

## How Has This Been Tested

Added and updated unit tests

## Types of changes

- [x] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by fharper — CHANGES_REQUESTED** [review]
Unless I don't use it correctly, there is an issue as I get the same value for the `type` and the `value` of the `customer company registrations` using the following:

```
customer_company_registrations = invoice_data.invoice.customer_company_registration

for customer_company_registration in customer_company_registrations:
    # To get the type of number
    customer_company_registration_number_type = customer_company_registration.type
    print ("\nCustomer Company Registration Type")
    print (customer_company_registration_number_type)

    # To get the company number
    customer_company_registration_number_value = customer_company_registration.value
    print ("\nCustomer Company Registration Number")
    print (customer_company_registration_number_value)
```

which give me

```
Customer Company Registration

Customer Company Registration Type
736952710

Customer Company Registration Number
736952710 
```

but when using the raw output, I get

```
        "customer_company_registration": [
          {
            "confidence": 0.99,
            "page_id": 0,
            "polygon": [
              [
                0.113,
                0.251
              ],
              [
                0.206,
                0.251
              ],
              [
                0.206,
                0.266
              ],
              [
                0.113,
                0.266
              ]
            ],
            "type": "TIN",
            "value": "736952710"
          }
        ],
```

**Comment by fharper** [comment]
Note to myself: once we have an approved version, we need to update the documentation since the customer company registration information is now in a list.

/cc @fakela

**Comment by ianardee** [comment]
> Unless I don't use it correctly, there is an issue as I get the same value for the `type` and the `value` of the `customer company registrations` using the following:
> 
> ```
> customer_company_registrations = invoice_data.invoice.customer_company_registration
> 
> for customer_company_registration in customer_company_registrations:
>     # To get the type of number
>     customer_company_registration_number_type = customer_company_registration.type
>     print ("\nCustomer Company Registration Type")
>     print (customer_company_registration_number_type)
> 
>     # To get the company number
>     customer_company_registration_number_value = customer_company_registration.value
>     print ("\nCustomer Company Registration Number")
>     print (customer_company_registration_number_value)
> ```
> 
> which give me
> 
> ```
> Customer Company Registration
> 
> Customer Company Registration Type
> 736952710
> 
> Customer Company Registration Number
> 736952710 
> ```

:facepalm: 

Thanks a bunch, fixed in 6d25b12b77625dea8c81d53e74e521f43f141ea5

**Review by fharper — CHANGES_REQUESTED** [review]
When I run `pytest` I get a bunch of weird errors, something missing in the PR?

```
====================================================== test session starts ======================================================
platform darwin -- Python 3.9.7, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /Users/fharper/Documents/code/mindee/sdk-python, configfile: setup.cfg
plugins: cov-2.12.1
collected 125 items / 1 error / 124 selected

============================================================ ERRORS =============================================================
________________________________________ ERROR collecting tests/documents/test_plate.py _________________________________________
ImportError while importing test module '/Users/fharper/Documents/code/mindee/sdk-python/tests/documents/test_plate.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../.pyenv/versions/3.9.7/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/documents/test_plate.py:5: in <module>
    from mindee import CarPlate
E   ImportError: cannot import name 'CarPlate' from 'mindee' (/Users/fharper/Documents/code/mindee/sdk-python/mindee/__init__.py)

---------- coverage: platform darwin, python 3.9.7-final-0 -----------
Name                                     Stmts   Miss  Cover   Missing
----------------------------------------------------------------------
mindee/__main__.py                          71     58    18%   37-46, 50-58, 63-98, 103-186, 191, 195
mindee/client.py                            86     53    38%   39-41, 59-96, 101-123, 129, 142-143, 169-183, 193-201, 211-219, 232-243, 253-261, 280-281, 304-309, 334-340, 365-371
mindee/document_config.py                   16      5    69%   22-26
mindee/documents/base.py                    34     16    53%   14-16, 33-42, 59, 63, 66, 69, 73
mindee/documents/car_plate.py               46     46     0%   1-131
mindee/documents/custom_document.py         20     12    40%   24, 39-43, 46-53, 56
mindee/documents/financial_document.py      94     76    19%   31-51, 66-100, 103, 147-152, 156, 166-193
mindee/documents/invoice.py                138    100    28%   46, 61-101, 106-112, 135-138, 142, 156-184, 193-222, 232-262, 274-289, 300-315, 324-332, 343-356
mindee/documents/passport.py               106     71    33%   38, 53-70, 73-79, 102-104, 108-109, 113, 129, 143-148, 156-161, 169-174, 182-184, 192-202, 213-230, 240-251, 262-274
mindee/documents/receipt.py                 70     43    39%   39, 47-48, 71-97, 103, 107-108, 118-146, 157-163, 172-180
mindee/fields/amount.py                     11      6    45%   24-35
mindee/fields/base.py                       65     47    28%   24-44, 56-58, 68-74, 84-90, 93-99, 102-104, 117-118, 121-123
mindee/fields/date.py                       19      9    53%   31-49
mindee/fields/locale.py                     25     15    40%   26-34, 38-40, 43-50
mindee/fields/orientation.py                13      9    31%   20-34
mindee/fields/payment_details.py            48     39    19%   37-74, 77-86
mindee/fields/tax.py                        32     25    22%   29-53, 56-63
mindee/http.py                              95     56    41%   50-62, 70-76, 80-83, 89-96, 112-121, 135-142, 154-161, 166-170, 181-185, 196-199
mindee/inputs.py                            95     62    35%   40-62, 70-72, 81-88, 96-115, 123-127, 145-151, 171-175, 197-202, 224-228
mindee/response.py                          24     15    38%   20-46, 75-78
mindee/versions.py                          12      1    92%   23
----------------------------------------------------------------------
TOTAL                                     1127    764    32%

4 files skipped due to complete coverage.

FAIL Required test coverage of 85% not reached. Total coverage: 32.21%
==================================================== short test summary info ====================================================
ERROR tests/documents/test_plate.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================================= 1 error in 0.64s ========================================================
```

**Comment by fharper** [comment]
> Thanks a bunch, fixed in https://github.com/mindee/mindee-api-python/commit/6d25b12b77625dea8c81d53e74e521f43f141ea5

It's working now, thanks

**Review by fharper — APPROVED** [review]
Forget the test issues, it was me! LGTM

**Pull request merged**
