### PR TITLE
chg: :sparkles: add CLI tool for testing and demo

### PR DESCRIPTION
**Pull request by ianardee**
# Add CLI tool for testing and demo

## Description

Add a CLI tool as `__main__.py` for quick debugging and testing.

## Motivation and Context

Useful when we need to run a single file through the SDK for testing mainly.

Also when debugging user issues.

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by fharper** [comment]
When calling using invoice and base64, I get this error:

```
Traceback (most recent call last):
  File "/Users/fharper/.pyenv/versions/3.9.7/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/fharper/.pyenv/versions/3.9.7/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/fharper/Dropbox/Mac (3)/Documents/code/mindee/sdk-python/mindee/__main__.py", line 119, in <module>
    call_endpoint(parse_args())
  File "/Users/fharper/Dropbox/Mac (3)/Documents/code/mindee/sdk-python/mindee/__main__.py", line 54, in call_endpoint
    file_handle.read(), args.input_type, cut_pdf=args.cut_pdf
  File "/Users/fharper/.pyenv/versions/3.9.7/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 10: invalid continuation byte
```

**Comment by fharper** [comment]
It doesn't seem to check for environment variable token either. I get this for the same comment but using `path` or `stream` 

```
Traceback (most recent call last):
  File "/Users/fharper/.pyenv/versions/3.9.7/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/fharper/.pyenv/versions/3.9.7/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/fharper/Dropbox/Mac (3)/Documents/code/mindee/sdk-python/mindee/__main__.py", line 119, in <module>
    call_endpoint(parse_args())
  File "/Users/fharper/Dropbox/Mac (3)/Documents/code/mindee/sdk-python/mindee/__main__.py", line 57, in call_endpoint
    parsed_data = parse_func(args.path, args.input_type, cut_pdf=args.cut_pdf)
  File "/Users/fharper/Dropbox/Mac (3)/Documents/code/mindee/sdk-python/mindee/__init__.py", line 213, in parse_invoice
    raise Exception("Missing 'invoice_token' arg in parse_invoice() function.")
Exception: Missing 'invoice_token' arg in parse_invoice() function.
```

while I have `MINDEE_INVOICE_TOKEN` set on my machine. I was able to test the rest using the `--invoice-key` parameter.

**Review by fharper — CHANGES_REQUESTED** [review]
Added some bugs. I assume the `base64` issue is SDK related, but the token one is about this cli.

**Comment by ianardee** [comment]
@fharper problem with the env var token is fixed, thanks.

**Comment by ianardee** [comment]
> When calling using `invoice` and `base64`, I get this error:
> 
> The same PDF works with `stream` & `file`

You need to supply an actual base64 encoded text file, but there was a missing parameter for specifying the filename (fixed).

This works for me:
```
./mindee-cli.sh receipt -i base64 -f receipt.pdf  ./tests/data/expense_receipts/receipt.txt
```

**Review by fharper — CHANGES_REQUESTED** [review]
when using `financial` I get this error

```
Traceback (most recent call last):
  File "/Users/fharper/.pyenv/versions/3.9.7/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/fharper/.pyenv/versions/3.9.7/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/fharper/Dropbox/Mac (3)/Documents/code/mindee/sdk-python/mindee/__main__.py", line 129, in <module>
    call_endpoint(parse_args())
  File "/Users/fharper/Dropbox/Mac (3)/Documents/code/mindee/sdk-python/mindee/__main__.py", line 61, in call_endpoint
    print(getattr(parsed_data, args.product_name))
AttributeError: 'Response' object has no attribute 'financial'
```

**Comment by fharper** [comment]
Also, I just realized that it's missing license plate API

**Comment by ianardee** [comment]
@fharper 
* fixed for financial document
* license plate has been removed from v2, so didn't add it to the CLI

**Review by fharper — APPROVED** [review]
LGTM

**Pull request merged**
