### PR TITLE
Version 2.2.1

### PR DESCRIPTION
**Pull request by ianardee**
### Fixes
* :bug: fix for locale constructor
* :bug: fix custom document in CLI
* :label: declare type info to mypy

### Changes
* :label: set stricter pylint and mypy settings
* :technologist: add pre-commit to ensure proper code formatting
* :art: fixes to import order (isort) and documentation (pydocstyle)

### CODE REVIEW

**Review by fharper — CHANGES_REQUESTED** [review]
When I run with the `parsed` output, I get this error:

```
➜ ./mindee-cli.sh invoice -i path ../datasets/invoices/1008e67d-01d5-41c8-9791-4a21892fb717.pdf -o parsed
Traceback (most recent call last):
  File "/Users/fharper/.pyenv/versions/3.9.7/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/fharper/.pyenv/versions/3.9.7/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/fharper/Documents/code/mindee/sdk-python/mindee/__main__.py", line 193, in <module>
    main()
  File "/Users/fharper/Documents/code/mindee/sdk-python/mindee/__main__.py", line 189, in main
    call_endpoint(_parse_args())
  File "/Users/fharper/Documents/code/mindee/sdk-python/mindee/__main__.py", line 94, in call_endpoint
    print(json.dumps(getattr(parsed_data, doc_type), indent=2, default=vars))
  File "/Users/fharper/.pyenv/versions/3.9.7/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Users/fharper/.pyenv/versions/3.9.7/lib/python3.9/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/Users/fharper/.pyenv/versions/3.9.7/lib/python3.9/json/encoder.py", line 439, in _iterencode
    yield from _iterencode(o, _current_indent_level)
  File "/Users/fharper/.pyenv/versions/3.9.7/lib/python3.9/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Users/fharper/.pyenv/versions/3.9.7/lib/python3.9/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Users/fharper/.pyenv/versions/3.9.7/lib/python3.9/json/encoder.py", line 439, in _iterencode
    yield from _iterencode(o, _current_indent_level)
  File "/Users/fharper/.pyenv/versions/3.9.7/lib/python3.9/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Users/fharper/.pyenv/versions/3.9.7/lib/python3.9/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Users/fharper/.pyenv/versions/3.9.7/lib/python3.9/json/encoder.py", line 438, in _iterencode
    o = _default(o)
TypeError: vars() argument must have __dict__ attribute
```

**Comment by fharper** [comment]
Also, typo (invlude_words) on this error when I try to use the ` -w` with passport: `Exception: invlude_words parameter cannot be set to True for passport API`

**Comment by fharper** [comment]
When there is no taxes or no taxes detected, we shouldn't show the `%` like

```
-----Receipt data-----
Filename: 013cff9e-10f1-467c-9f8d-fee04200b43f.jpg
Total amount including taxes: 13.72
Total amount excluding taxes: 11.72
Date: 2018-07-16
Category: transport
Time: 16:40
Merchant name:
Taxes: 2.0 None%
Total taxes: 2.0
Locale: en-US; en; US; USD;
----------------------
```

**Comment by fharper** [comment]
I found things during my tests for this PR, that may not be about this PR, so let me know and I can create ProductBoard card or issues here if it's the case.

**Comment by fharper** [comment]
Outside of those, LGTM.

**Comment by ianardee** [comment]
@fharper yeah all those are probably not related to this PR, since the code didn't change (apart from import order which should have zero impact).

Nevertheless, might as well push these fixes here.

**Comment by ianardee** [comment]
> Also, typo (invlude_words) on this error when I try to use the ` -w` with passport: `Exception: invlude_words parameter cannot be set to True for passport API`

@fharper fixed in 4dfa24558f1196db66fc180cd555e26365d14bb8

**Comment by ianardee** [comment]
> When I run with the `parsed` output, I get this error:
> 
> ```
> ➜ ./mindee-cli.sh invoice -i path ../datasets/invoices/1008e67d-01d5-41c8-9791-4a21892fb717.pdf -o parsed
> Traceback (most recent call last):
>   File "/Users/fharper/.pyenv/versions/3.9.7/lib/python3.9/runpy.py", line 197, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/Users/fharper/.pyenv/versions/3.9.7/lib/python3.9/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/Users/fharper/Documents/code/mindee/sdk-python/mindee/__main__.py", line 193, in <module>
>     main()
>   File "/Users/fharper/Documents/code/mindee/sdk-python/mindee/__main__.py", line 189, in main
>     call_endpoint(_parse_args())
>   File "/Users/fharper/Documents/code/mindee/sdk-python/mindee/__main__.py", line 94, in call_endpoint
>     print(json.dumps(getattr(parsed_data, doc_type), indent=2, default=vars))
>   File "/Users/fharper/.pyenv/versions/3.9.7/lib/python3.9/json/__init__.py", line 234, in dumps
>     return cls(
>   File "/Users/fharper/.pyenv/versions/3.9.7/lib/python3.9/json/encoder.py", line 201, in encode
>     chunks = list(chunks)
>   File "/Users/fharper/.pyenv/versions/3.9.7/lib/python3.9/json/encoder.py", line 439, in _iterencode
>     yield from _iterencode(o, _current_indent_level)
>   File "/Users/fharper/.pyenv/versions/3.9.7/lib/python3.9/json/encoder.py", line 431, in _iterencode
>     yield from _iterencode_dict(o, _current_indent_level)
>   File "/Users/fharper/.pyenv/versions/3.9.7/lib/python3.9/json/encoder.py", line 405, in _iterencode_dict
>     yield from chunks
>   File "/Users/fharper/.pyenv/versions/3.9.7/lib/python3.9/json/encoder.py", line 439, in _iterencode
>     yield from _iterencode(o, _current_indent_level)
>   File "/Users/fharper/.pyenv/versions/3.9.7/lib/python3.9/json/encoder.py", line 431, in _iterencode
>     yield from _iterencode_dict(o, _current_indent_level)
>   File "/Users/fharper/.pyenv/versions/3.9.7/lib/python3.9/json/encoder.py", line 405, in _iterencode_dict
>     yield from chunks
>   File "/Users/fharper/.pyenv/versions/3.9.7/lib/python3.9/json/encoder.py", line 438, in _iterencode
>     o = _default(o)
> TypeError: vars() argument must have __dict__ attribute
> ```

@fharper fixed in f67a4372e85fc2557e6f8ecd6ee7aca3b9af7343

**Comment by ianardee** [comment]
> When there is no taxes or no taxes detected, we shouldn't show the `%` like
> 
> ```
> -----Receipt data-----
> Filename: 013cff9e-10f1-467c-9f8d-fee04200b43f.jpg
> Total amount including taxes: 13.72
> Total amount excluding taxes: 11.72
> Date: 2018-07-16
> Category: transport
> Time: 16:40
> Merchant name:
> Taxes: 2.0 None%
> Total taxes: 2.0
> Locale: en-US; en; US; USD;
> ----------------------
> ```

@fharper I'm not able to reproduce, even after updating unit tests in f67a4372e85fc2557e6f8ecd6ee7aca3b9af7343

Can you send me the file please?

**Review by fharper — APPROVED** [review]
LGTM

**Pull request merged**
